package:
  name: rdflib-jsonld
  version: "0.3"

source:
  fn: rdflib-jsonld-0.3.tar.gz
  url: https://pypi.python.org/packages/source/r/rdflib-jsonld/rdflib-jsonld-0.3.tar.gz
  md5: 653083508e904bfd2c240b03a446d6c2
#  patches:
   # List any patch files here
   # - fix.patch

build:
  preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - rdflib-jsonld = rdflib-jsonld:main
    #
    # Would create an entry point called rdflib-jsonld that calls rdflib-jsonld.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - rdflib >=4.2

  run:
    - python
    - setuptools
    - rdflib >=4.2

test:
  # Python imports
  imports:
    - rdflib_jsonld

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/RDFLib/rdflib-jsonld
  license: BSD License
  summary: 'rdflib extension adding JSON-LD parser and serializer'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
